blank_issues_enabled: false

contact_links:
  - name: Ask a Question
    url: https://github.com/PaulERayburn/Shortcuts-Custom-Release/discussions
    about: Have a question? Start a discussion instead of opening an issue.
